declare module 'react-native-ico-mingcute-tiny-bold-filled' {
    import { ReactNode } from 'react';
    import { SvgProps, AdditionalProps } from 'react-native-svg';

    type iconNames = 'add-circle' |
      'aiming-2' |
      'aiming' |
      'airbnb' |
      'airplane' |
      'airplay' |
      'alarm-1' |
      'alarm-2' |
      'album-2' |
      'album' |
      'alert-octagon' |
      'alert' |
      'align-bottom' |
      'align-center' |
      'align-horizontal-center' |
      'align-left-2' |
      'align-left' |
      'align-right-2' |
      'align-right' |
      'align-top' |
      'align-vertical-center' |
      'alipay' |
      'anchor' |
      'and' |
      'android-2' |
      'android' |
      'anticlockwise' |
      'apple' |
      'arrow-left-down' |
      'arrow-left' |
      'arrow-right' |
      'arrow-up' |
      'asterisk' |
      'at' |
      'attachment-2' |
      'attachment' |
      'auction' |
      'award' |
      'az-sort-ascending-letters' |
      'baby-carriage' |
      'back-2' |
      'back' |
      'badge' |
      'bank-card' |
      'bank' |
      'basket' |
      'battery-charging' |
      'battery' |
      'beard' |
      'bike' |
      'bling' |
      'bluetooth-off' |
      'bluetooth' |
      'body' |
      'bold' |
      'book-2' |
      'book-3' |
      'book-4' |
      'book-5' |
      'book-6' |
      'book' |
      'bookmark' |
      'border-blank' |
      'border-bottom' |
      'border-horizontal' |
      'border-inner' |
      'border-left' |
      'border-outer' |
      'border-radius' |
      'border-top' |
      'border-vertical' |
      'bowl' |
      'box-2' |
      'box-3' |
      'box' |
      'braces' |
      'brackets' |
      'bread' |
      'bridge-2' |
      'bridge' |
      'briefcase' |
      'brightness' |
      'brush-2' |
      'brush' |
      'bug' |
      'building-1' |
      'building-2' |
      'building-3' |
      'building-4' |
      'bulb' |
      'bus-2' |
      'bus' |
      'cake' |
      'calendar' |
      'camcorder' |
      'camera-2' |
      'camera' |
      'campground' |
      'candle' |
      'car-2' |
      'car' |
      'ceiling-lamp' |
      'cellphone-vibration' |
      'cellphone' |
      'certificate-2' |
      'certificate' |
      'charging-pile' |
      'chart-bar' |
      'chart-line' |
      'chart-pie' |
      'chat-1' |
      'chat-2' |
      'chat-3' |
      'check-circle' |
      'check' |
      'chip' |
      'chrome' |
      'clapperboard' |
      'clipboard' |
      'clock-2' |
      'clock' |
      'clockwise' |
      'close-circle' |
      'close' |
      'cloud-lightning' |
      'cloud-snow' |
      'cloud' |
      'code' |
      'coin-2' |
      'coin' |
      'color-filter' |
      'color-picker' |
      'column' |
      'columns-2' |
      'columns-3' |
      'command' |
      'comment' |
      'compass' |
      'computer-camera-off' |
      'computer-camera' |
      'computer' |
      'contacts' |
      'copper-coin' |
      'copy-2' |
      'copy-3' |
      'copy' |
      'copyright' |
      'counter-2' |
      'counter' |
      'coupon' |
      'currency-bitcoin-2' |
      'currency-bitcoin' |
      'currency-cny' |
      'currency-dollar' |
      'currency-euro' |
      'cursor' |
      'dashboard-2' |
      'dashboard' |
      'delete-2' |
      'delete-back' |
      'delete' |
      'department' |
      'desk-lamp' |
      'desk' |
      'device' |
      'diamond' |
      'diary' |
      'directions' |
      'directory' |
      'disc' |
      'discord' |
      'distribute-spacing-horizontal' |
      'distribute-spacing-vertical' |
      'dividing-line' |
      'doc' |
      'document-2' |
      'document-3' |
      'document' |
      'documents' |
      'door' |
      'dot-grid' |
      'down' |
      'download-2' |
      'download-3' |
      'download' |
      'dribbble' |
      'drink' |
      'drop' |
      'ear' |
      'earth' |
      'ebike' |
      'edit-2' |
      'edit-3' |
      'edit' |
      'emoji-2' |
      'emoji' |
      'enter-door' |
      'entrance' |
      'eraser' |
      'exchange-bitcoin-2' |
      'exchange-bitcoin' |
      'exchange-cny' |
      'exchange-dollar' |
      'exchange-euro' |
      'exit-door' |
      'exit' |
      'external-link' |
      'eye-2' |
      'eye-close' |
      'eye' |
      'eyebrow' |
      'eyeglass' |
      'face' |
      'facebook' |
      'faceid' |
      'factory' |
      'fast-forward' |
      'fast-rewind' |
      'female' |
      'file-certificate' |
      'file-check' |
      'file-code' |
      'file-download' |
      'file-export' |
      'file-import' |
      'file-infor' |
      'file-more' |
      'file-music' |
      'file-new' |
      'file-search' |
      'file-star' |
      'file-unknown' |
      'file-upload' |
      'file-warning' |
      'file-zip' |
      'file' |
      'film' |
      'filter-2' |
      'filter-3' |
      'filter' |
      'fingerprint' |
      'fire' |
      'fish' |
      'flag-1' |
      'flag-2' |
      'flag-3' |
      'flag-4' |
      'flash' |
      'flashlight' |
      'flask-2' |
      'flask' |
      'flight-land' |
      'flight-takeoff' |
      'flip-horizontal' |
      'flip-vertical' |
      'flower-2' |
      'flower' |
      'folder-2' |
      'folder-open-2' |
      'folder-open' |
      'folder' |
      'font-size' |
      'font' |
      'foot' |
      'forbid-circle' |
      'formula' |
      'forward-2' |
      'forward' |
      'frame' |
      'fridge' |
      'fullscreen-2' |
      'fullscreen-exit-2' |
      'fullscreen-exit' |
      'fullscreen' |
      'game-1' |
      'game-2' |
      'gas-station' |
      'ghost' |
      'gift' |
      'git-branch' |
      'git-commit' |
      'git-compare' |
      'git-lab' |
      'git-merge' |
      'git-pull-request-close' |
      'git-pull-request' |
      'github' |
      'glass-cup' |
      'globe' |
      'google-play' |
      'google' |
      'greatwall' |
      'grid-2' |
      'grid' |
      'group' |
      'hair-2' |
      'hair' |
      'hashtag' |
      'heading-1' |
      'heading-2' |
      'heading-3' |
      'headphone-2' |
      'headphone' |
      'heart' |
      'hexagon' |
      'history' |
      'home-1' |
      'home-2' |
      'home-3' |
      'home-4' |
      'home-5' |
      'home-6' |
      'horn' |
      'hospital' |
      'hotkey' |
      'idcard' |
      'imac' |
      'inbox-2' |
      'inbox' |
      'indent-decrease' |
      'indent-increase' |
      'information' |
      'ins' |
      'invite' |
      'italic' |
      'key-1' |
      'key-2' |
      'keyboard' |
      'knife' |
      'lantern' |
      'laptop' |
      'layout-10' |
      'layout-11' |
      'layout-2' |
      'layout-3' |
      'layout-4' |
      'layout-5' |
      'layout-6' |
      'layout-7' |
      'layout-8' |
      'layout-9' |
      'layout-bottom' |
      'layout-grid' |
      'layout-left' |
      'layout-right' |
      'layout-top' |
      'layout' |
      'left' |
      'letter-spacing' |
      'lifebuoy' |
      'lighthouse' |
      'lightning' |
      'line-height' |
      'link-2' |
      'link' |
      'linkedin' |
      'list-check-2' |
      'list-check-3' |
      'list-check' |
      'list-ordered' |
      'live-location' |
      'live-photo' |
      'location-2' |
      'location' |
      'lock' |
      'lollipop' |
      'luggage' |
      'magic-1' |
      'magic-2' |
      'mail-open' |
      'mail-send' |
      'mail' |
      'mailbox' |
      'male' |
      'map-pin' |
      'map' |
      'mark-pen' |
      'markup' |
      'medal' |
      'medium' |
      'menu' |
      'message-1' |
      'message-2' |
      'message-3' |
      'message-4' |
      'messenger' |
      'meta' |
      'mic-2' |
      'mic-off' |
      'mic' |
      'microphone' |
      'microscope' |
      'mingcute' |
      'minimize' |
      'minus-circle' |
      'moment' |
      'monument' |
      'moon-cloudy' |
      'moon-stars' |
      'moon' |
      'more-1' |
      'more-2' |
      'more-3' |
      'more-4' |
      'mortarboard' |
      'mosaic' |
      'mouse' |
      'mouth' |
      'move' |
      'movie' |
      'music-2' |
      'music-3' |
      'music' |
      'navigation' |
      'news' |
      'nose' |
      'notebook-2' |
      'notebook' |
      'notification-off' |
      'notification' |
      'octagon' |
      'omega' |
      'open-door' |
      'pad' |
      'paint-2' |
      'paint-brush' |
      'paint' |
      'palace-2' |
      'palace' |
      'palette-2' |
      'palette' |
      'paper' |
      'paragraph' |
      'parentheses' |
      'paster' |
      'pause-circle' |
      'pause' |
      'pavilion' |
      'paypal' |
      'pdf' |
      'pen-2' |
      'pen' |
      'pencil' |
      'pentagon' |
      'performance' |
      'phone-add' |
      'phone-block' |
      'phone-call' |
      'phone-incoming' |
      'phone-outgoing' |
      'phone-success' |
      'phone' |
      'pic-2' |
      'pic' |
      'pin-2' |
      'pin' |
      'pinterest' |
      'planet' |
      'play-circle' |
      'play' |
      'plugin-2' |
      'plugin' |
      'power' |
      'ppt' |
      'presentation-1' |
      'presentation-2' |
      'print' |
      'profile' |
      'qq' |
      'qrcode' |
      'question' |
      'quill-pen' |
      'quote-left' |
      'quote-right' |
      'radar-2' |
      'radar' |
      'radio' |
      'rain' |
      'react' |
      'receive-money' |
      'red-packet-open' |
      'red-packet' |
      'reddit' |
      'refresh-1' |
      'refresh-2' |
      'remote' |
      'repeat-one' |
      'repeat' |
      'restore' |
      'riding' |
      'right' |
      'road' |
      'rocket-2' |
      'rocket' |
      'round' |
      'route' |
      'rows-2' |
      'rows-3' |
      'rows-4' |
      'ruler' |
      'run' |
      'safe-alert' |
      'safe-box' |
      'safe-flash' |
      'safe-lock' |
      'safe-shield-2' |
      'safe-shield' |
      'safety-certificate' |
      'sale' |
      'sandglass' |
      'save-2' |
      'save' |
      'scale' |
      'scan-2' |
      'scan' |
      'schedule' |
      'school' |
      'science' |
      'scissors-2' |
      'scissors-3' |
      'scissors' |
      'scooter' |
      'screenshot' |
      'seal' |
      'search-2' |
      'search-3' |
      'search' |
      'send-plane' |
      'server' |
      'service' |
      'settings-1' |
      'settings-2' |
      'settings-3' |
      'settings-4' |
      'settings-5' |
      'share-2' |
      'share-3' |
      'share-forward' |
      'shield-shape' |
      'shield' |
      'ship' |
      'shopping-bag-1' |
      'shopping-bag-2' |
      'shopping-cart-1' |
      'shopping-cart-2' |
      'shuffle' |
      'skip-forward' |
      'skip-previous' |
      'snapchat' |
      'snow' |
      'sort-ascending' |
      'sort-descending' |
      'spacing-horizontal' |
      'spacing-vertical' |
      'sparkles' |
      'speaker' |
      'spotify' |
      'square' |
      'star' |
      'stock' |
      'stop-circle' |
      'stop' |
      'stopwatch' |
      'store-2' |
      'store' |
      'strikethrough' |
      'sun-cloudy' |
      'sun' |
      'sunrise' |
      'sunset' |
      'switch' |
      't-shirt' |
      'table-2' |
      'table' |
      'tag' |
      'target' |
      'teacup' |
      'telegram' |
      'telescope' |
      'terminal-box' |
      'terminal' |
      'text' |
      'thermometer' |
      'thumb-down' |
      'thumb-up' |
      'tiktok' |
      'time' |
      'toggle-left-2' |
      'toggle-left' |
      'toggle-right-2' |
      'toggle-right' |
      'tool' |
      'tower-2' |
      'tower-3' |
      'tower-4' |
      'tower-5' |
      'tower' |
      'traffic-cone' |
      'train-2' |
      'train' |
      'transfer-2' |
      'transfer-3' |
      'transfer-4' |
      'transfer' |
      'translate' |
      'triangle' |
      'trophy' |
      'truck' |
      'tv-1' |
      'tv-2' |
      'twitter' |
      'typhoon' |
      'ufo' |
      'umbrella' |
      'underline' |
      'unlink-2' |
      'unlink' |
      'unlock' |
      'up' |
      'upload-2' |
      'upload-3' |
      'upload' |
      'user-1' |
      'user-2' |
      'user-3' |
      'user-4' |
      'user-5' |
      'user-add' |
      'user-follow' |
      'user-remove' |
      'vector-bezier-2' |
      'vector-bezier-3' |
      'vector-bezier' |
      'version' |
      'video' |
      'vip-1' |
      'vip-2' |
      'vip-3' |
      'vip-4' |
      'vkontakte' |
      'voice' |
      'volume-mute' |
      'volume-off' |
      'volume' |
      'vue' |
      'walk' |
      'wallet-2' |
      'wallet-3' |
      'wallet-4' |
      'wallet' |
      'warning' |
      'wastebasket' |
      'watch' |
      'web' |
      'wechat' |
      'weibo' |
      'whatsapp' |
      'wifi-off' |
      'wifi' |
      'wind' |
      'windows' |
      'wineglass-2' |
      'wineglass' |
      'world-2' |
      'world' |
      'xls' |
      'youtube' |
      'za-sort-descending-letters' |
      'zoom-in' |
      'zoom-out';

    type backgroundType = 'circle' | 'rect' | 'button';

    type positionType = 'top' | 'bottom' | 'right' | 'left' |
      'top_right' | 'top_left' | 'bottom_right' | 'bottom_left';

    type backgroundTypeObj = {
      type?: backgroundType;
      color?: string;
      radius?: number;
      borderRadius?: number;
    };

    type badgeTypeObj = {
      value?: number | string;
      fontSize?: string;
      position?: positionType;
      color?: string;
      backgroundColor?: string;
      radius?: number;
    };

    interface IconProps {
      name: iconNames;
      width?: number;
      height?: number;
      color?: string;
      stroke?: number;
      background?: backgroundType | backgroundTypeObj;
      badge?: number | string | badgeTypeObj;
    }

    const Icon: (props: IconProps & SvgProps & AdditionalProps) => ReactNode;

    export { iconNames };
    export default Icon;
}
